<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504005903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol_code VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_169E6FB9D723AECA ON course (symbol_code)');
        $this->addSql('CREATE TABLE payment_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84BBD50BA76ED395 ON payment_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_84BBD50B591CC992 ON payment_transaction (course_id)');
        $this->addSql('ALTER TABLE payment_transaction ADD CONSTRAINT FK_84BBD50BA76ED395 FOREIGN KEY (user_id) REFERENCES billing_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_transaction ADD CONSTRAINT FK_84BBD50B591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE payment_transaction DROP CONSTRAINT FK_84BBD50BA76ED395');
        $this->addSql('ALTER TABLE payment_transaction DROP CONSTRAINT FK_84BBD50B591CC992');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE payment_transaction');
    }
}
