<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504005903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE billing_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, balance DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON billing_user (email)');
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol_code VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_169E6FB9D723AECA ON course (symbol_code)');
        $this->addSql('CREATE TABLE refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9A29DF3E52A7F1F ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE INDEX IDX_9A29DF3EF85E0677 ON refresh_tokens (username)');
        $this->addSql('CREATE TABLE payment_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84BBD50BA76ED395 ON payment_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_84BBD50B591CC992 ON payment_transaction (course_id)');
        $this->addSql('ALTER TABLE payment_transaction ADD CONSTRAINT FK_84BBD50BA76ED395 FOREIGN KEY (user_id) REFERENCES billing_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_transaction ADD CONSTRAINT FK_84BBD50B591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE payment_transaction DROP CONSTRAINT FK_84BBD50BA76ED395');
        $this->addSql('ALTER TABLE payment_transaction DROP CONSTRAINT FK_84BBD50B591CC992');
        $this->addSql('DROP TABLE payment_transaction');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE billing_user');
    }
}
